[2025-01-22T08:41:25.116+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T08:41:25.125+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_snowflake_job2.dbt_tasks.dbt-debug manual__2025-01-22T08:30:13.938951+00:00 [queued]>
[2025-01-22T08:41:25.130+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_snowflake_job2.dbt_tasks.dbt-debug manual__2025-01-22T08:30:13.938951+00:00 [queued]>
[2025-01-22T08:41:25.132+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 4
[2025-01-22T08:41:25.151+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): dbt_tasks.dbt-debug> on 2025-01-22 08:30:13.938951+00:00
[2025-01-22T08:41:25.155+0000] {standard_task_runner.py:72} INFO - Started process 36176 to run task
[2025-01-22T08:41:25.158+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_snowflake_job2', 'dbt_tasks.dbt-debug', 'manual__2025-01-22T08:30:13.938951+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflake.py', '--cfg-path', '/tmp/tmp4gndyj59']
[2025-01-22T08:41:25.160+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask dbt_tasks.dbt-debug
[2025-01-22T08:41:25.220+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_snowflake_job2.dbt_tasks.dbt-debug manual__2025-01-22T08:30:13.938951+00:00 [running]> on host LAPTOP-3U4JI4R2.
[2025-01-22T08:41:25.277+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_snowflake_job2' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt-debug' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T08:30:13.938951+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T08:30:13.938951+00:00'
[2025-01-22T08:41:25.280+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-22T08:41:25.281+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-22T08:41:25.283+0000] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt-debug state:running start_date:2025-01-22 08:41:25.126894+00:00
[2025-01-22T08:41:25.284+0000] {logging_mixin.py:190} INFO - Dag name:dbt_snowflake_job2 and current dag run status:running
[2025-01-22T08:41:25.285+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T08:41:25.287+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-22T08:41:25.288+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug --profiles-dir /mnt/c/Users/psara/.dbt --project-dir /mnt/c/Users/psara/shrovandbtsnowflake']
[2025-01-22T08:41:25.293+0000] {subprocess.py:99} INFO - Output:
[2025-01-22T08:41:25.344+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: dbt: command not found
[2025-01-22T08:41:25.345+0000] {subprocess.py:110} INFO - Command exited with return code 127
[2025-01-22T08:41:25.351+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-01-22T08:41:25.376+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-22T08:41:25.377+0000] {logging_mixin.py:190} INFO - Task start:2025-01-22 08:41:25.126894+00:00 end:2025-01-22 08:41:25.375643+00:00 duration:0.248749
[2025-01-22T08:41:25.379+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): dbt_tasks.dbt-debug> dag:<DAG: dbt_snowflake_job2> dagrun:<DagRun dbt_snowflake_job2 @ 2025-01-22 08:30:13.938951+00:00: manual__2025-01-22T08:30:13.938951+00:00, state:running, queued_at: 2025-01-22 08:30:13.968495+00:00. externally triggered: True>
[2025-01-22T08:41:25.380+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2025-01-22T08:41:25.381+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_snowflake_job2, task_id=dbt_tasks.dbt-debug, run_id=manual__2025-01-22T08:30:13.938951+00:00, execution_date=20250122T083013, start_date=20250122T084125, end_date=20250122T084125
[2025-01-22T08:41:25.411+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T08:41:25.413+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task dbt_tasks.dbt-debug (Bash command failed. The command returned a non-zero exit code 127.; 36176)
Traceback (most recent call last):
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-01-22T08:41:25.462+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-22T08:41:25.475+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-22T08:41:25.477+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
