[2025-01-22T08:06:42.070+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T08:06:42.078+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_snowflake_job1.dbt_tasks.dbt-debug scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-01-22T08:06:42.083+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_snowflake_job1.dbt_tasks.dbt-debug scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-01-22T08:06:42.085+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-01-22T08:06:42.106+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): dbt_tasks.dbt-debug> on 2025-01-21 00:00:00+00:00
[2025-01-22T08:06:42.109+0000] {standard_task_runner.py:72} INFO - Started process 27582 to run task
[2025-01-22T08:06:42.112+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_snowflake_job1', 'dbt_tasks.dbt-debug', 'scheduled__2025-01-21T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflake.py', '--cfg-path', '/tmp/tmpnkqjv2qs']
[2025-01-22T08:06:42.114+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask dbt_tasks.dbt-debug
[2025-01-22T08:06:42.175+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_snowflake_job1.dbt_tasks.dbt-debug scheduled__2025-01-21T00:00:00+00:00 [running]> on host LAPTOP-3U4JI4R2.
[2025-01-22T08:06:42.268+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_snowflake_job1' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt-debug' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-21T00:00:00+00:00'
[2025-01-22T08:06:42.272+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-22T08:06:42.274+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-22T08:06:42.276+0000] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt-debug state:running start_date:2025-01-22 08:06:42.080021+00:00
[2025-01-22T08:06:42.278+0000] {logging_mixin.py:190} INFO - Dag name:dbt_snowflake_job1 and current dag run status:running
[2025-01-22T08:06:42.279+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T08:06:42.281+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-22T08:06:42.282+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug --profiles-dir /mnt/c/Users/psara/.dbt --project-dit /mnt/c/Users/psara/shrovandbtsnowflake']
[2025-01-22T08:06:42.287+0000] {subprocess.py:99} INFO - Output:
[2025-01-22T08:06:42.345+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: dbt: command not found
[2025-01-22T08:06:42.346+0000] {subprocess.py:110} INFO - Command exited with return code 127
[2025-01-22T08:06:42.389+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-01-22T08:06:42.420+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-22T08:06:42.422+0000] {logging_mixin.py:190} INFO - Task start:2025-01-22 08:06:42.080021+00:00 end:2025-01-22 08:06:42.420240+00:00 duration:0.340219
[2025-01-22T08:06:42.423+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): dbt_tasks.dbt-debug> dag:<DAG: dbt_snowflake_job1> dagrun:<DagRun dbt_snowflake_job1 @ 2025-01-21 00:00:00+00:00: scheduled__2025-01-21T00:00:00+00:00, state:running, queued_at: 2025-01-22 08:06:24.318290+00:00. externally triggered: False>
[2025-01-22T08:06:42.424+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2025-01-22T08:06:42.425+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_snowflake_job1, task_id=dbt_tasks.dbt-debug, run_id=scheduled__2025-01-21T00:00:00+00:00, execution_date=20250121T000000, start_date=20250122T080642, end_date=20250122T080642
[2025-01-22T08:06:42.447+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T08:06:42.448+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task dbt_tasks.dbt-debug (Bash command failed. The command returned a non-zero exit code 127.; 27582)
Traceback (most recent call last):
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-01-22T08:06:42.502+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-22T08:06:42.516+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-22T08:06:42.518+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-22T08:16:28.372+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T08:16:28.382+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_snowflake_job1.dbt_tasks.dbt-debug scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-01-22T08:16:28.390+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_snowflake_job1.dbt_tasks.dbt-debug scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-01-22T08:16:28.391+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-01-22T08:16:28.435+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): dbt_tasks.dbt-debug> on 2025-01-21 00:00:00+00:00
[2025-01-22T08:16:28.442+0000] {standard_task_runner.py:72} INFO - Started process 30002 to run task
[2025-01-22T08:16:28.449+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_snowflake_job1', 'dbt_tasks.dbt-debug', 'scheduled__2025-01-21T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflake.py', '--cfg-path', '/tmp/tmpe42310w_']
[2025-01-22T08:16:28.452+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask dbt_tasks.dbt-debug
[2025-01-22T08:16:28.506+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_snowflake_job1.dbt_tasks.dbt-debug scheduled__2025-01-21T00:00:00+00:00 [running]> on host LAPTOP-3U4JI4R2.
[2025-01-22T08:16:28.599+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_snowflake_job1' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt-debug' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-21T00:00:00+00:00'
[2025-01-22T08:16:28.601+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-22T08:16:28.603+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-22T08:16:28.604+0000] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt-debug state:running start_date:2025-01-22 08:16:28.384143+00:00
[2025-01-22T08:16:28.606+0000] {logging_mixin.py:190} INFO - Dag name:dbt_snowflake_job1 and current dag run status:running
[2025-01-22T08:16:28.607+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T08:16:28.609+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-22T08:16:28.612+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug --profiles-dir /mnt/c/Users/psara/.dbt --project-dit /mnt/c/Users/psara/shrovandbtsnowflake']
[2025-01-22T08:16:28.617+0000] {subprocess.py:99} INFO - Output:
[2025-01-22T08:16:28.671+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: dbt: command not found
[2025-01-22T08:16:28.672+0000] {subprocess.py:110} INFO - Command exited with return code 127
[2025-01-22T08:16:28.679+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-01-22T08:16:28.709+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-22T08:16:28.711+0000] {logging_mixin.py:190} INFO - Task start:2025-01-22 08:16:28.384143+00:00 end:2025-01-22 08:16:28.709332+00:00 duration:0.325189
[2025-01-22T08:16:28.712+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): dbt_tasks.dbt-debug> dag:<DAG: dbt_snowflake_job1> dagrun:<DagRun dbt_snowflake_job1 @ 2025-01-21 00:00:00+00:00: scheduled__2025-01-21T00:00:00+00:00, state:running, queued_at: 2025-01-22 08:16:10.047232+00:00. externally triggered: False>
[2025-01-22T08:16:28.714+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2025-01-22T08:16:28.715+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_snowflake_job1, task_id=dbt_tasks.dbt-debug, run_id=scheduled__2025-01-21T00:00:00+00:00, execution_date=20250121T000000, start_date=20250122T081628, end_date=20250122T081628
[2025-01-22T08:16:28.748+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T08:16:28.750+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task dbt_tasks.dbt-debug (Bash command failed. The command returned a non-zero exit code 127.; 30002)
Traceback (most recent call last):
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-01-22T08:16:28.801+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-22T08:16:28.815+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-22T08:16:28.817+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
