[2025-01-22T13:05:39.663+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T13:05:39.673+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_dbt_snowflake1.dbt_tasks.dbt-run manual__2025-01-22T13:02:36.854235+00:00 [queued]>
[2025-01-22T13:05:39.679+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_dbt_snowflake1.dbt_tasks.dbt-run manual__2025-01-22T13:02:36.854235+00:00 [queued]>
[2025-01-22T13:05:39.681+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-01-22T13:05:39.722+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): dbt_tasks.dbt-run> on 2025-01-22 13:02:36.854235+00:00
[2025-01-22T13:05:39.727+0000] {standard_task_runner.py:72} INFO - Started process 102343 to run task
[2025-01-22T13:05:39.730+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'airflow_dbt_snowflake1', 'dbt_tasks.dbt-run', 'manual__2025-01-22T13:02:36.854235+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflake.py', '--cfg-path', '/tmp/tmp_f1g0_6e']
[2025-01-22T13:05:39.732+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask dbt_tasks.dbt-run
[2025-01-22T13:05:39.779+0000] {task_command.py:467} INFO - Running <TaskInstance: airflow_dbt_snowflake1.dbt_tasks.dbt-run manual__2025-01-22T13:02:36.854235+00:00 [running]> on host LAPTOP-3U4JI4R2.
[2025-01-22T13:05:39.875+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airflow_dbt_snowflake1' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt-run' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T13:02:36.854235+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T13:02:36.854235+00:00'
[2025-01-22T13:05:39.877+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-22T13:05:39.879+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-22T13:05:39.880+0000] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt-run state:running start_date:2025-01-22 13:05:39.675291+00:00
[2025-01-22T13:05:39.881+0000] {logging_mixin.py:190} INFO - Dag name:airflow_dbt_snowflake1 and current dag run status:running
[2025-01-22T13:05:39.883+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T13:05:39.885+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-22T13:05:39.886+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /mnt/c/Users/psara/.dbt --project-dir /mnt/c/Users/psara/shrovandbtsnowflake']
[2025-01-22T13:05:39.893+0000] {subprocess.py:99} INFO - Output:
[2025-01-22T13:05:52.840+0000] {subprocess.py:106} INFO - [0m13:05:52  Running with dbt=1.9.1
[2025-01-22T13:05:56.166+0000] {subprocess.py:106} INFO - [0m13:05:56  Registered adapter: snowflake=1.9.0
[2025-01-22T13:06:07.202+0000] {subprocess.py:106} INFO - [0m13:06:07  Encountered an error:
[2025-01-22T13:06:07.203+0000] {subprocess.py:106} INFO - 'dbt_snowflake://macros/metadata.sql'
[2025-01-22T13:06:07.209+0000] {subprocess.py:106} INFO - [0m13:06:07  Traceback (most recent call last):
[2025-01-22T13:06:07.210+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 153, in wrapper
[2025-01-22T13:06:07.212+0000] {subprocess.py:106} INFO -     result, success = func(*args, **kwargs)
[2025-01-22T13:06:07.213+0000] {subprocess.py:106} INFO -                       ^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T13:06:07.214+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 103, in wrapper
[2025-01-22T13:06:07.215+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-01-22T13:06:07.216+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T13:06:07.217+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 235, in wrapper
[2025-01-22T13:06:07.218+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-01-22T13:06:07.218+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T13:06:07.219+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 264, in wrapper
[2025-01-22T13:06:07.220+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-01-22T13:06:07.221+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T13:06:07.221+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 311, in wrapper
[2025-01-22T13:06:07.222+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-01-22T13:06:07.223+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T13:06:07.224+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 327, in wrapper
[2025-01-22T13:06:07.225+0000] {subprocess.py:106} INFO -     setup_manifest(ctx, write=write, write_perf_info=write_perf_info)
[2025-01-22T13:06:07.226+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 351, in setup_manifest
[2025-01-22T13:06:07.227+0000] {subprocess.py:106} INFO -     ctx.obj["manifest"] = parse_manifest(
[2025-01-22T13:06:07.228+0000] {subprocess.py:106} INFO -                           ^^^^^^^^^^^^^^^
[2025-01-22T13:06:07.228+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/parser/manifest.py", line 2061, in parse_manifest
[2025-01-22T13:06:07.229+0000] {subprocess.py:106} INFO -     manifest = ManifestLoader.get_full_manifest(
[2025-01-22T13:06:07.230+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T13:06:07.231+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/parser/manifest.py", line 312, in get_full_manifest
[2025-01-22T13:06:07.231+0000] {subprocess.py:106} INFO -     manifest = loader.load()
[2025-01-22T13:06:07.232+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^
[2025-01-22T13:06:07.233+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/parser/manifest.py", line 381, in load
[2025-01-22T13:06:07.233+0000] {subprocess.py:106} INFO -     self.load_and_parse_macros(project_parser_files)
[2025-01-22T13:06:07.234+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/parser/manifest.py", line 682, in load_and_parse_macros
[2025-01-22T13:06:07.235+0000] {subprocess.py:106} INFO -     block = FileBlock(self.manifest.files[file_id])
[2025-01-22T13:06:07.235+0000] {subprocess.py:106} INFO -                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
[2025-01-22T13:06:07.236+0000] {subprocess.py:106} INFO - KeyError: 'dbt_snowflake://macros/metadata.sql'
[2025-01-22T13:06:07.237+0000] {subprocess.py:106} INFO - 
[2025-01-22T13:06:08.729+0000] {subprocess.py:110} INFO - Command exited with return code 2
[2025-01-22T13:06:08.741+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-01-22T13:06:08.778+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-22T13:06:08.780+0000] {logging_mixin.py:190} INFO - Task start:2025-01-22 13:05:39.675291+00:00 end:2025-01-22 13:06:08.778214+00:00 duration:29.102923
[2025-01-22T13:06:08.781+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): dbt_tasks.dbt-run> dag:<DAG: airflow_dbt_snowflake1> dagrun:<DagRun airflow_dbt_snowflake1 @ 2025-01-22 13:02:36.854235+00:00: manual__2025-01-22T13:02:36.854235+00:00, state:running, queued_at: 2025-01-22 13:02:36.931610+00:00. externally triggered: True>
[2025-01-22T13:06:08.782+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 2.
[2025-01-22T13:06:08.783+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=airflow_dbt_snowflake1, task_id=dbt_tasks.dbt-run, run_id=manual__2025-01-22T13:02:36.854235+00:00, execution_date=20250122T130236, start_date=20250122T130539, end_date=20250122T130608
[2025-01-22T13:06:08.817+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T13:06:08.818+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 41 for task dbt_tasks.dbt-run (Bash command failed. The command returned a non-zero exit code 2.; 102343)
Traceback (most recent call last):
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-01-22T13:06:08.853+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-22T13:06:08.864+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-22T13:06:08.866+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
