[2025-01-22T11:33:31.980+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T11:33:31.987+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_dbt_snowflake.dbt_tasks.dbt-run manual__2025-01-22T11:20:35.273729+00:00 [queued]>
[2025-01-22T11:33:31.992+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_dbt_snowflake.dbt_tasks.dbt-run manual__2025-01-22T11:20:35.273729+00:00 [queued]>
[2025-01-22T11:33:31.994+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 4
[2025-01-22T11:33:32.020+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): dbt_tasks.dbt-run> on 2025-01-22 11:20:35.273729+00:00
[2025-01-22T11:33:32.027+0000] {standard_task_runner.py:72} INFO - Started process 77112 to run task
[2025-01-22T11:33:32.031+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'airflow_dbt_snowflake', 'dbt_tasks.dbt-run', 'manual__2025-01-22T11:20:35.273729+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflake.py', '--cfg-path', '/tmp/tmpwmjaoi1m']
[2025-01-22T11:33:32.033+0000] {standard_task_runner.py:105} INFO - Job 34: Subtask dbt_tasks.dbt-run
[2025-01-22T11:33:32.077+0000] {task_command.py:467} INFO - Running <TaskInstance: airflow_dbt_snowflake.dbt_tasks.dbt-run manual__2025-01-22T11:20:35.273729+00:00 [running]> on host LAPTOP-3U4JI4R2.
[2025-01-22T11:33:32.178+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airflow_dbt_snowflake' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt-run' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T11:20:35.273729+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T11:20:35.273729+00:00'
[2025-01-22T11:33:32.180+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-22T11:33:32.182+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-22T11:33:32.183+0000] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt-run state:running start_date:2025-01-22 11:33:31.988997+00:00
[2025-01-22T11:33:32.184+0000] {logging_mixin.py:190} INFO - Dag name:airflow_dbt_snowflake and current dag run status:running
[2025-01-22T11:33:32.186+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T11:33:32.188+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-22T11:33:32.189+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /mnt/c/Users/psara/.dbt --project-dir /mnt/c/Users/psara/shrovandbtsnowflake']
[2025-01-22T11:33:32.195+0000] {subprocess.py:99} INFO - Output:
[2025-01-22T11:33:41.581+0000] {subprocess.py:106} INFO - [0m11:33:41  Running with dbt=1.9.1
[2025-01-22T11:33:44.590+0000] {subprocess.py:106} INFO - [0m11:33:44  Registered adapter: snowflake=1.9.0
[2025-01-22T11:33:54.697+0000] {subprocess.py:106} INFO - [0m11:33:54  Encountered an error:
[2025-01-22T11:33:54.699+0000] {subprocess.py:106} INFO - 'dbt_snowflake://macros/adapters.sql'
[2025-01-22T11:33:54.705+0000] {subprocess.py:106} INFO - [0m11:33:54  Traceback (most recent call last):
[2025-01-22T11:33:54.706+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 153, in wrapper
[2025-01-22T11:33:54.707+0000] {subprocess.py:106} INFO -     result, success = func(*args, **kwargs)
[2025-01-22T11:33:54.707+0000] {subprocess.py:106} INFO -                       ^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T11:33:54.708+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 103, in wrapper
[2025-01-22T11:33:54.709+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-01-22T11:33:54.710+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T11:33:54.710+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 235, in wrapper
[2025-01-22T11:33:54.711+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-01-22T11:33:54.712+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T11:33:54.713+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 264, in wrapper
[2025-01-22T11:33:54.713+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-01-22T11:33:54.714+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T11:33:54.714+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 311, in wrapper
[2025-01-22T11:33:54.715+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-01-22T11:33:54.716+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T11:33:54.716+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 327, in wrapper
[2025-01-22T11:33:54.717+0000] {subprocess.py:106} INFO -     setup_manifest(ctx, write=write, write_perf_info=write_perf_info)
[2025-01-22T11:33:54.718+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 351, in setup_manifest
[2025-01-22T11:33:54.718+0000] {subprocess.py:106} INFO -     ctx.obj["manifest"] = parse_manifest(
[2025-01-22T11:33:54.719+0000] {subprocess.py:106} INFO -                           ^^^^^^^^^^^^^^^
[2025-01-22T11:33:54.720+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/parser/manifest.py", line 2061, in parse_manifest
[2025-01-22T11:33:54.721+0000] {subprocess.py:106} INFO -     manifest = ManifestLoader.get_full_manifest(
[2025-01-22T11:33:54.721+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T11:33:54.722+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/parser/manifest.py", line 312, in get_full_manifest
[2025-01-22T11:33:54.723+0000] {subprocess.py:106} INFO -     manifest = loader.load()
[2025-01-22T11:33:54.724+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^
[2025-01-22T11:33:54.724+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/parser/manifest.py", line 381, in load
[2025-01-22T11:33:54.725+0000] {subprocess.py:106} INFO -     self.load_and_parse_macros(project_parser_files)
[2025-01-22T11:33:54.726+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/parser/manifest.py", line 682, in load_and_parse_macros
[2025-01-22T11:33:54.727+0000] {subprocess.py:106} INFO -     block = FileBlock(self.manifest.files[file_id])
[2025-01-22T11:33:54.728+0000] {subprocess.py:106} INFO -                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
[2025-01-22T11:33:54.728+0000] {subprocess.py:106} INFO - KeyError: 'dbt_snowflake://macros/adapters.sql'
[2025-01-22T11:33:54.729+0000] {subprocess.py:106} INFO - 
[2025-01-22T11:33:56.166+0000] {subprocess.py:110} INFO - Command exited with return code 2
[2025-01-22T11:33:56.174+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-01-22T11:33:56.197+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-22T11:33:56.199+0000] {logging_mixin.py:190} INFO - Task start:2025-01-22 11:33:31.988997+00:00 end:2025-01-22 11:33:56.197403+00:00 duration:24.208406
[2025-01-22T11:33:56.201+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): dbt_tasks.dbt-run> dag:<DAG: airflow_dbt_snowflake> dagrun:<DagRun airflow_dbt_snowflake @ 2025-01-22 11:20:35.273729+00:00: manual__2025-01-22T11:20:35.273729+00:00, state:running, queued_at: 2025-01-22 11:20:35.294143+00:00. externally triggered: True>
[2025-01-22T11:33:56.202+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 2.
[2025-01-22T11:33:56.203+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=airflow_dbt_snowflake, task_id=dbt_tasks.dbt-run, run_id=manual__2025-01-22T11:20:35.273729+00:00, execution_date=20250122T112035, start_date=20250122T113331, end_date=20250122T113356
[2025-01-22T11:33:56.237+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T11:33:56.239+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 34 for task dbt_tasks.dbt-run (Bash command failed. The command returned a non-zero exit code 2.; 77112)
Traceback (most recent call last):
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-01-22T11:33:56.270+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-22T11:33:56.280+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-22T11:33:56.282+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
