[2025-01-22T11:12:43.663+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T11:12:43.671+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_dbt_snowflake.dbt_tasks.dbt-run scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-01-22T11:12:43.677+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_dbt_snowflake.dbt_tasks.dbt-run scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-01-22T11:12:43.678+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 4
[2025-01-22T11:12:43.706+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): dbt_tasks.dbt-run> on 2025-01-21 00:00:00+00:00
[2025-01-22T11:12:43.709+0000] {standard_task_runner.py:72} INFO - Started process 72477 to run task
[2025-01-22T11:12:43.712+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'airflow_dbt_snowflake', 'dbt_tasks.dbt-run', 'scheduled__2025-01-21T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflake.py', '--cfg-path', '/tmp/tmpbc9q5oba']
[2025-01-22T11:12:43.715+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask dbt_tasks.dbt-run
[2025-01-22T11:12:43.765+0000] {task_command.py:467} INFO - Running <TaskInstance: airflow_dbt_snowflake.dbt_tasks.dbt-run scheduled__2025-01-21T00:00:00+00:00 [running]> on host LAPTOP-3U4JI4R2.
[2025-01-22T11:12:43.849+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airflow_dbt_snowflake' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt-run' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-21T00:00:00+00:00'
[2025-01-22T11:12:43.851+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-22T11:12:43.853+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-22T11:12:43.854+0000] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt-run state:running start_date:2025-01-22 11:12:43.673184+00:00
[2025-01-22T11:12:43.855+0000] {logging_mixin.py:190} INFO - Dag name:airflow_dbt_snowflake and current dag run status:running
[2025-01-22T11:12:43.856+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T11:12:43.858+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-22T11:12:43.861+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /mnt/c/Users/psara/.dbt --project-dir /mnt/c/Users/psara/shrovandbtsnowflake']
[2025-01-22T11:12:43.866+0000] {subprocess.py:99} INFO - Output:
[2025-01-22T11:12:59.251+0000] {subprocess.py:106} INFO - [0m11:12:59  Running with dbt=1.9.1
[2025-01-22T11:13:05.105+0000] {subprocess.py:106} INFO - [0m11:13:05  Registered adapter: snowflake=1.9.0
[2025-01-22T11:13:16.140+0000] {subprocess.py:106} INFO - [0m11:13:16  Encountered an error:
[2025-01-22T11:13:16.141+0000] {subprocess.py:106} INFO - 'dbt_snowflake://macros/catalog.sql'
[2025-01-22T11:13:16.146+0000] {subprocess.py:106} INFO - [0m11:13:16  Traceback (most recent call last):
[2025-01-22T11:13:16.147+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 153, in wrapper
[2025-01-22T11:13:16.148+0000] {subprocess.py:106} INFO -     result, success = func(*args, **kwargs)
[2025-01-22T11:13:16.149+0000] {subprocess.py:106} INFO -                       ^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T11:13:16.149+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 103, in wrapper
[2025-01-22T11:13:16.150+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-01-22T11:13:16.151+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T11:13:16.152+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 235, in wrapper
[2025-01-22T11:13:16.153+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-01-22T11:13:16.153+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T11:13:16.154+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 264, in wrapper
[2025-01-22T11:13:16.155+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-01-22T11:13:16.155+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T11:13:16.156+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 311, in wrapper
[2025-01-22T11:13:16.157+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-01-22T11:13:16.158+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T11:13:16.158+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 327, in wrapper
[2025-01-22T11:13:16.159+0000] {subprocess.py:106} INFO -     setup_manifest(ctx, write=write, write_perf_info=write_perf_info)
[2025-01-22T11:13:16.160+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 351, in setup_manifest
[2025-01-22T11:13:16.160+0000] {subprocess.py:106} INFO -     ctx.obj["manifest"] = parse_manifest(
[2025-01-22T11:13:16.161+0000] {subprocess.py:106} INFO -                           ^^^^^^^^^^^^^^^
[2025-01-22T11:13:16.162+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/parser/manifest.py", line 2061, in parse_manifest
[2025-01-22T11:13:16.162+0000] {subprocess.py:106} INFO -     manifest = ManifestLoader.get_full_manifest(
[2025-01-22T11:13:16.163+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-22T11:13:16.164+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/parser/manifest.py", line 312, in get_full_manifest
[2025-01-22T11:13:16.165+0000] {subprocess.py:106} INFO -     manifest = loader.load()
[2025-01-22T11:13:16.165+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^
[2025-01-22T11:13:16.166+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/parser/manifest.py", line 381, in load
[2025-01-22T11:13:16.167+0000] {subprocess.py:106} INFO -     self.load_and_parse_macros(project_parser_files)
[2025-01-22T11:13:16.167+0000] {subprocess.py:106} INFO -   File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/dbt/parser/manifest.py", line 682, in load_and_parse_macros
[2025-01-22T11:13:16.168+0000] {subprocess.py:106} INFO -     block = FileBlock(self.manifest.files[file_id])
[2025-01-22T11:13:16.169+0000] {subprocess.py:106} INFO -                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
[2025-01-22T11:13:16.169+0000] {subprocess.py:106} INFO - KeyError: 'dbt_snowflake://macros/catalog.sql'
[2025-01-22T11:13:16.170+0000] {subprocess.py:106} INFO - 
[2025-01-22T11:13:17.715+0000] {subprocess.py:110} INFO - Command exited with return code 2
[2025-01-22T11:13:17.722+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-01-22T11:13:17.749+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-22T11:13:17.749+0000] {logging_mixin.py:190} INFO - Task start:2025-01-22 11:12:43.673184+00:00 end:2025-01-22 11:13:17.748616+00:00 duration:34.075432
[2025-01-22T11:13:17.751+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): dbt_tasks.dbt-run> dag:<DAG: airflow_dbt_snowflake> dagrun:<DagRun airflow_dbt_snowflake @ 2025-01-21 00:00:00+00:00: scheduled__2025-01-21T00:00:00+00:00, state:running, queued_at: 2025-01-22 10:59:40.597449+00:00. externally triggered: False>
[2025-01-22T11:13:17.751+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 2.
[2025-01-22T11:13:17.752+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=airflow_dbt_snowflake, task_id=dbt_tasks.dbt-run, run_id=scheduled__2025-01-21T00:00:00+00:00, execution_date=20250121T000000, start_date=20250122T111243, end_date=20250122T111317
[2025-01-22T11:13:17.789+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T11:13:17.792+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 26 for task dbt_tasks.dbt-run (Bash command failed. The command returned a non-zero exit code 2.; 72477)
Traceback (most recent call last):
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
