[2025-01-22T08:07:00.644+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T08:07:00.675+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_snowflake_job1.dbt_tasks.dbt-debug manual__2025-01-22T08:06:23.283532+00:00 [queued]>
[2025-01-22T08:07:00.682+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_snowflake_job1.dbt_tasks.dbt-debug manual__2025-01-22T08:06:23.283532+00:00 [queued]>
[2025-01-22T08:07:00.684+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-01-22T08:07:00.714+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): dbt_tasks.dbt-debug> on 2025-01-22 08:06:23.283532+00:00
[2025-01-22T08:07:00.718+0000] {standard_task_runner.py:72} INFO - Started process 27645 to run task
[2025-01-22T08:07:00.721+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_snowflake_job1', 'dbt_tasks.dbt-debug', 'manual__2025-01-22T08:06:23.283532+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflake.py', '--cfg-path', '/tmp/tmppisubmid']
[2025-01-22T08:07:00.723+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask dbt_tasks.dbt-debug
[2025-01-22T08:07:00.785+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_snowflake_job1.dbt_tasks.dbt-debug manual__2025-01-22T08:06:23.283532+00:00 [running]> on host LAPTOP-3U4JI4R2.
[2025-01-22T08:07:00.881+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_snowflake_job1' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt-debug' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T08:06:23.283532+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T08:06:23.283532+00:00'
[2025-01-22T08:07:00.884+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-22T08:07:00.886+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-22T08:07:00.888+0000] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt-debug state:running start_date:2025-01-22 08:07:00.676929+00:00
[2025-01-22T08:07:00.889+0000] {logging_mixin.py:190} INFO - Dag name:dbt_snowflake_job1 and current dag run status:running
[2025-01-22T08:07:00.890+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T08:07:00.892+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-22T08:07:00.894+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug --profiles-dir /mnt/c/Users/psara/.dbt --project-dit /mnt/c/Users/psara/shrovandbtsnowflake']
[2025-01-22T08:07:00.911+0000] {subprocess.py:99} INFO - Output:
[2025-01-22T08:07:00.980+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: dbt: command not found
[2025-01-22T08:07:00.981+0000] {subprocess.py:110} INFO - Command exited with return code 127
[2025-01-22T08:07:00.991+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-01-22T08:07:01.026+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-22T08:07:01.028+0000] {logging_mixin.py:190} INFO - Task start:2025-01-22 08:07:00.676929+00:00 end:2025-01-22 08:07:01.024731+00:00 duration:0.347802
[2025-01-22T08:07:01.029+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): dbt_tasks.dbt-debug> dag:<DAG: dbt_snowflake_job1> dagrun:<DagRun dbt_snowflake_job1 @ 2025-01-22 08:06:23.283532+00:00: manual__2025-01-22T08:06:23.283532+00:00, state:running, queued_at: 2025-01-22 08:06:23.323865+00:00. externally triggered: True>
[2025-01-22T08:07:01.030+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2025-01-22T08:07:01.030+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_snowflake_job1, task_id=dbt_tasks.dbt-debug, run_id=manual__2025-01-22T08:06:23.283532+00:00, execution_date=20250122T080623, start_date=20250122T080700, end_date=20250122T080701
[2025-01-22T08:07:01.059+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T08:07:01.061+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task dbt_tasks.dbt-debug (Bash command failed. The command returned a non-zero exit code 127.; 27645)
Traceback (most recent call last):
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/psara/shrovandbtairflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-01-22T08:07:01.099+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-22T08:07:01.114+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-22T08:07:01.116+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
